version: '3'

volumes:
  db:
  static:
  media:

services:
  web:
    build:
      dockerfile: Dockerfile
      context: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      - media:/app/media
      - static:/app/static
    depends_on:
      - backend
  
  database:
    image: "postgres:13-alpine"
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - /var/lib/postgresql/data

  backend:
    build: .
    image: "movies:latest"
    environment:
      DEBUG: 1
    restart: always
    volumes:
      - media:/app/media
      - static:/app/static
    ports:
      - 8000:8000
    depends_on:
      - database
