version: "3"
   
volumes:
    db:
    static:

services:

   database:
    image: "postgres:13-alpine"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psswd
      POSTGRES_DB: movies
    volumes:
      - db:/var/lib/postgresql/data


   web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./media:/app/media
      - static:/app/static
    env_file: 
      - .env
    depends_on: 
      - "database"


   frontend:  
    build: ./nginx
    restart: always
    environment:
      SERVER_NAME: "movies"
      API_HOST: "backend:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./media:/app/media
      - static:/app/static
    depends_on:
      - "web"
